version: "3.3"
services:
  mongo:
    image: mongo
  memcached:
    image: memcached

  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
      MEMCACHED_ADDRS: "memcached:11211"
    depends_on:
      - mongo
      - memcached

  cleaner:
    build: .
    entrypoint: ./cleaner
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo
